//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAMODEL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.QuestionOption = new HashSet<QuestionOption>();
        }
    
        public int ID { get; set; }
        public string QuestionDefinition { get; set; }
        public int EducationProgramID { get; set; }
        public int LessonID { get; set; }
        public int SubjectID { get; set; }
        public int DifficultyID { get; set; }
        public int QuestionTypeID { get; set; }
        public byte LanguageID { get; set; }
        public bool State { get; set; }
    
        public virtual Difficulty Difficulty { get; set; }
        public virtual EducationProgram EducationProgram { get; set; }
        public virtual Language Language { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionOption> QuestionOption { get; set; }
    }
}
